# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2_mtgm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(599, 365)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/task_mainwindow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 591, 361))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setMovable(True)
        self.tabWidget.setProperty("tabBarAutoHide", False)
        self.tabWidget.setObjectName("tabWidget")
        self.task_GM = QtWidgets.QWidget()
        self.task_GM.setEnabled(True)
        self.task_GM.setObjectName("task_GM")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.task_GM)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 20, 331, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox = QtWidgets.QGroupBox(self.task_GM)
        self.groupBox.setGeometry(QtCore.QRect(350, 20, 221, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showtodaytask = QtWidgets.QPushButton(self.groupBox)
        self.showtodaytask.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showtodaytask.sizePolicy().hasHeightForWidth())
        self.showtodaytask.setSizePolicy(sizePolicy)
        self.showtodaytask.setMinimumSize(QtCore.QSize(20, 10))
        self.showtodaytask.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(11)
        self.showtodaytask.setFont(font)
        self.showtodaytask.setIconSize(QtCore.QSize(40, 40))
        self.showtodaytask.setObjectName("showtodaytask")
        self.verticalLayout.addWidget(self.showtodaytask)
        self.showalltask = QtWidgets.QPushButton(self.groupBox)
        self.showalltask.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(11)
        self.showalltask.setFont(font)
        self.showalltask.setIconSize(QtCore.QSize(40, 40))
        self.showalltask.setObjectName("showalltask")
        self.verticalLayout.addWidget(self.showalltask)
        self.updatetask = QtWidgets.QPushButton(self.groupBox)
        self.updatetask.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(11)
        self.updatetask.setFont(font)
        self.updatetask.setIconSize(QtCore.QSize(40, 40))
        self.updatetask.setObjectName("updatetask")
        self.verticalLayout.addWidget(self.updatetask)
        self.add_del_task = QtWidgets.QPushButton(self.groupBox)
        self.add_del_task.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(11)
        self.add_del_task.setFont(font)
        self.add_del_task.setIconSize(QtCore.QSize(40, 40))
        self.add_del_task.setObjectName("add_del_task")
        self.verticalLayout.addWidget(self.add_del_task)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/tasks.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.task_GM, icon1, "")
        self.shiftchange_GM = QtWidgets.QWidget()
        self.shiftchange_GM.setObjectName("shiftchange_GM")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/JJB.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.shiftchange_GM, icon2, "")
        self.sg_GM = QtWidgets.QWidget()
        self.sg_GM.setObjectName("sg_GM")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/SQJ.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sg_GM, icon3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "测量管理"))
        self.groupBox.setTitle(_translate("Form", "任务操作"))
        self.showtodaytask.setText(_translate("Form", "今天任务状态"))
        self.showalltask.setText(_translate("Form", "显示全部任务"))
        self.updatetask.setText(_translate("Form", "计划任务更新"))
        self.add_del_task.setText(_translate("Form", "添加删除任务"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.task_GM), _translate("Form", "任务管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shiftchange_GM), _translate("Form", "交接班管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sg_GM), _translate("Form", "送取件管理"))

