# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui3_dialog_task.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_task(object):
    def setupUi(self, Dialog_task):
        Dialog_task.setObjectName("Dialog_task")
        Dialog_task.resize(1188, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/todaytaskwindow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_task.setWindowIcon(icon)
        Dialog_task.setStatusTip("")
        Dialog_task.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tasktable = QtWidgets.QTableWidget(Dialog_task)
        self.tasktable.setEnabled(True)
        self.tasktable.setGeometry(QtCore.QRect(0, 0, 1011, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasktable.sizePolicy().hasHeightForWidth())
        self.tasktable.setSizePolicy(sizePolicy)
        self.tasktable.setAutoScroll(True)
        self.tasktable.setGridStyle(QtCore.Qt.SolidLine)
        self.tasktable.setRowCount(20)
        self.tasktable.setColumnCount(10)
        self.tasktable.setObjectName("tasktable")
        item = QtWidgets.QTableWidgetItem()
        self.tasktable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setStrikeOut(False)
        item.setFont(font)
        self.tasktable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tasktable.setItem(0, 1, item)
        self.tasktable.horizontalHeader().setHighlightSections(True)
        self.tasktable.horizontalHeader().setSortIndicatorShown(False)
        self.tasktable.verticalHeader().setVisible(False)
        self.tasktable.verticalHeader().setCascadingSectionResizes(False)
        self.tasktable.verticalHeader().setHighlightSections(False)
        self.tasktable.verticalHeader().setSortIndicatorShown(False)
        self.tasktable.verticalHeader().setStretchLastSection(False)
        self.layoutWidget = QtWidgets.QWidget(Dialog_task)
        self.layoutWidget.setGeometry(QtCore.QRect(1040, 120, 121, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.refresh.setObjectName("refresh")
        self.verticalLayout.addWidget(self.refresh)
        self.change = QtWidgets.QPushButton(self.layoutWidget)
        self.change.setObjectName("change")
        self.verticalLayout.addWidget(self.change)
        self.resettask = QtWidgets.QPushButton(self.layoutWidget)
        self.resettask.setObjectName("resettask")
        self.verticalLayout.addWidget(self.resettask)
        self.savechanged = QtWidgets.QPushButton(self.layoutWidget)
        self.savechanged.setObjectName("savechanged")
        self.verticalLayout.addWidget(self.savechanged)

        self.retranslateUi(Dialog_task)
        QtCore.QMetaObject.connectSlotsByName(Dialog_task)

    def retranslateUi(self, Dialog_task):
        _translate = QtCore.QCoreApplication.translate
        Dialog_task.setWindowTitle(_translate("Dialog_task", "Dialog"))
        item = self.tasktable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_task", "index"))
        item = self.tasktable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_task", "任务名称"))
        item = self.tasktable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_task", "任务数量"))
        item = self.tasktable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_task", "预计送检时间"))
        item = self.tasktable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_task", "预计取件时间"))
        item = self.tasktable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_task", "测量类别"))
        item = self.tasktable.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_task", "取消任务"))
        item = self.tasktable.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_task", "更换任务"))
        item = self.tasktable.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_task", "备注"))
        item = self.tasktable.horizontalHeaderItem(9)
        item.setText(_translate("Dialog_task", "测量过程"))
        __sortingEnabled = self.tasktable.isSortingEnabled()
        self.tasktable.setSortingEnabled(False)
        self.tasktable.setSortingEnabled(__sortingEnabled)
        self.refresh.setText(_translate("Dialog_task", "刷新"))
        self.change.setText(_translate("Dialog_task", "更改任务状态"))
        self.resettask.setText(_translate("Dialog_task", "重置今天任务"))
        self.savechanged.setText(_translate("Dialog_task", "保存"))

