# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui5_dialog_addtask.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_addtask(object):
    def setupUi(self, Dialog_addtask):
        Dialog_addtask.setObjectName("Dialog_addtask")
        Dialog_addtask.resize(1004, 989)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/todaytaskwindow.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_addtask.setWindowIcon(icon)
        Dialog_addtask.setStatusTip("")
        Dialog_addtask.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addtasktable = QtWidgets.QTableWidget(Dialog_addtask)
        self.addtasktable.setEnabled(True)
        self.addtasktable.setGeometry(QtCore.QRect(0, 60, 1003, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addtasktable.sizePolicy().hasHeightForWidth())
        self.addtasktable.setSizePolicy(sizePolicy)
        self.addtasktable.setAutoScroll(True)
        self.addtasktable.setGridStyle(QtCore.Qt.SolidLine)
        self.addtasktable.setRowCount(1)
        self.addtasktable.setColumnCount(10)
        self.addtasktable.setObjectName("addtasktable")
        item = QtWidgets.QTableWidgetItem()
        self.addtasktable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setStrikeOut(False)
        item.setFont(font)
        self.addtasktable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.addtasktable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.addtasktable.setItem(0, 1, item)
        self.addtasktable.horizontalHeader().setHighlightSections(True)
        self.addtasktable.horizontalHeader().setSortIndicatorShown(False)
        self.addtasktable.verticalHeader().setVisible(False)
        self.addtasktable.verticalHeader().setCascadingSectionResizes(False)
        self.addtasktable.verticalHeader().setHighlightSections(False)
        self.addtasktable.verticalHeader().setSortIndicatorShown(False)
        self.addtasktable.verticalHeader().setStretchLastSection(False)
        self.label = QtWidgets.QLabel(Dialog_addtask)
        self.label.setGeometry(QtCore.QRect(121, 11, 174, 34))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog_addtask)
        self.line.setGeometry(QtCore.QRect(0, 200, 751, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tasktable = QtWidgets.QTableWidget(Dialog_addtask)
        self.tasktable.setEnabled(True)
        self.tasktable.setGeometry(QtCore.QRect(0, 330, 1003, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tasktable.sizePolicy().hasHeightForWidth())
        self.tasktable.setSizePolicy(sizePolicy)
        self.tasktable.setAutoScroll(True)
        self.tasktable.setGridStyle(QtCore.Qt.SolidLine)
        self.tasktable.setRowCount(20)
        self.tasktable.setColumnCount(10)
        self.tasktable.setObjectName("tasktable")
        item = QtWidgets.QTableWidgetItem()
        self.tasktable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setStrikeOut(False)
        item.setFont(font)
        self.tasktable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tasktable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tasktable.setItem(0, 1, item)
        self.tasktable.horizontalHeader().setHighlightSections(True)
        self.tasktable.horizontalHeader().setSortIndicatorShown(False)
        self.tasktable.verticalHeader().setVisible(False)
        self.tasktable.verticalHeader().setCascadingSectionResizes(False)
        self.tasktable.verticalHeader().setHighlightSections(False)
        self.tasktable.verticalHeader().setSortIndicatorShown(False)
        self.tasktable.verticalHeader().setStretchLastSection(False)
        self.label_2 = QtWidgets.QLabel(Dialog_addtask)
        self.label_2.setGeometry(QtCore.QRect(120, 260, 116, 34))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog_addtask)
        self.calendarWidget.setGeometry(QtCore.QRect(750, 140, 248, 169))
        self.calendarWidget.setObjectName("calendarWidget")
        self.layoutWidget = QtWidgets.QWidget(Dialog_addtask)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 150, 234, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comfirm_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(16)
        self.comfirm_btn.setFont(font)
        self.comfirm_btn.setObjectName("comfirm_btn")
        self.horizontalLayout.addWidget(self.comfirm_btn)
        self.comfirm_btn_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(16)
        self.comfirm_btn_2.setFont(font)
        self.comfirm_btn_2.setObjectName("comfirm_btn_2")
        self.horizontalLayout.addWidget(self.comfirm_btn_2)
        self.del_btn = QtWidgets.QPushButton(Dialog_addtask)
        self.del_btn.setGeometry(QtCore.QRect(480, 250, 134, 32))
        font = QtGui.QFont()
        font.setFamily("方正兰亭黑_GBK")
        font.setPointSize(16)
        self.del_btn.setFont(font)
        self.del_btn.setObjectName("del_btn")
        self.layoutWidget.raise_()
        self.addtasktable.raise_()
        self.label.raise_()
        self.tasktable.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.calendarWidget.raise_()
        self.del_btn.raise_()

        self.retranslateUi(Dialog_addtask)
        QtCore.QMetaObject.connectSlotsByName(Dialog_addtask)

    def retranslateUi(self, Dialog_addtask):
        _translate = QtCore.QCoreApplication.translate
        Dialog_addtask.setWindowTitle(_translate("Dialog_addtask", "Dialog"))
        item = self.addtasktable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_addtask", "index"))
        item = self.addtasktable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_addtask", "任务名称"))
        item = self.addtasktable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_addtask", "任务数量"))
        item = self.addtasktable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_addtask", "预计送检时间"))
        item = self.addtasktable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_addtask", "预计取件时间"))
        item = self.addtasktable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_addtask", "测量类别"))
        item = self.addtasktable.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_addtask", "取消任务"))
        item = self.addtasktable.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_addtask", "更换任务"))
        item = self.addtasktable.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_addtask", "备注"))
        item = self.addtasktable.horizontalHeaderItem(9)
        item.setText(_translate("Dialog_addtask", "测量过程"))
        __sortingEnabled = self.addtasktable.isSortingEnabled()
        self.addtasktable.setSortingEnabled(False)
        self.addtasktable.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog_addtask", "添加今天任务"))
        item = self.tasktable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_addtask", "index"))
        item = self.tasktable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_addtask", "任务名称"))
        item = self.tasktable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_addtask", "任务数量"))
        item = self.tasktable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_addtask", "预计送检时间"))
        item = self.tasktable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_addtask", "预计取件时间"))
        item = self.tasktable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_addtask", "测量类别"))
        item = self.tasktable.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_addtask", "取消任务"))
        item = self.tasktable.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_addtask", "更换任务"))
        item = self.tasktable.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_addtask", "备注"))
        item = self.tasktable.horizontalHeaderItem(9)
        item.setText(_translate("Dialog_addtask", "测量过程"))
        __sortingEnabled = self.tasktable.isSortingEnabled()
        self.tasktable.setSortingEnabled(False)
        self.tasktable.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Dialog_addtask", "今天任务"))
        self.comfirm_btn.setText(_translate("Dialog_addtask", "确认添加"))
        self.comfirm_btn_2.setText(_translate("Dialog_addtask", "刷新今天任务"))
        self.del_btn.setText(_translate("Dialog_addtask", "删除选中任务"))

